# Generated by Django 4.2.11 on 2025-07-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MachineSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('bolt_types', models.TextField(blank=True)),
                ('running_belt_size', models.CharField(blank=True, max_length=100)),
                ('motor_model', models.CharField(blank=True, max_length=100)),
                ('lcb_model', models.CharField(blank=True, max_length=100)),
                ('incline_motor', models.CharField(blank=True, max_length=100)),
                ('speed_sensor', models.CharField(blank=True, max_length=100)),
                ('lubricant_type', models.CharField(blank=True, max_length=100)),
                ('voltage_rating', models.CharField(blank=True, max_length=50)),
                ('current_rating', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('manual_file', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
            ],
            options={
                'unique_together': {('brand', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('quantity_in_stock', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('compatible_models', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('treadmill', 'Treadmill'), ('elliptical', 'Elliptical'), ('bike', 'Exercise Bike')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(default='Good', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'In Maintenance')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('value_tier', models.CharField(choices=[('low', 'Low Tier'), ('medium', 'Medium Tier'), ('high', 'High Tier'), ('commercial', 'Commercial Grade')], default='low', max_length=20)),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.machinespecification')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Treadmill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.customer')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.machinespecification')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField()),
                ('date_due', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.customer')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.rentalmachine')),
            ],
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('date_used', models.DateField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.job')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.part')),
                ('rental_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.rentalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.technician'),
        ),
        migrations.AddField(
            model_name='job',
            name='treadmill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.treadmill'),
        ),
    ]
