# Generated by Django 4.2.11 on 2025-07-29 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='rentalrecord',
            old_name='date_due',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='rentalrecord',
            old_name='date_returned',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='rentalrecord',
            old_name='date_out',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='treadmill',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='staff.customer'),
        ),
        migrations.AlterField(
            model_name='rentalrecord',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to='staff.rentalmachine'),
        ),
        migrations.AlterField(
            model_name='rentalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
