# Generated by Django 3.2.25 on 2025-08-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='suburb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
