# Generated by Django 4.2.23 on 2025-08-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20250813_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.customer'),
        ),
        migrations.AddField(
            model_name='job',
            name='rental_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.rentalmachine'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('to_assess', 'To be assessed'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='to_assess', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='treadmill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.treadmill'),
        ),
    ]
