# Generated by Django 4.2.23 on 2025-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_job_booking_date_job_confirmed_job_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='external_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='external_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
